### PR TITLE
Update wiki URLs

### PR DESCRIPTION
**Pull request by zaelgohary**
### Description

Update wiki URLs in all solutions & md files

### Related Issues

- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/79

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings

### CODE REVIEW

**Review by Mahmoud-Emad — APPROVED** [review]

**Review by AhmedHanafy725 — CHANGES_REQUESTED** [review]
there are some links not on the new wiki so let's wait till they are added and update them all together

**Comment by zaelgohary** [comment]
@AhmedHanafy725 I opened an issue for the missing docs [here](https://github.com/threefoldtech/info_grid/issues/64)

**Review by AhmedHanafy725 — COMMENTED** [review]
why do some links use https://www2.manual.grid.tf? all should be using the main one. if the main manual is not updated to the latest, please ask to deploy it

**Comment by zaelgohary** [comment]
Created an [issue](https://github.com/threefoldtech/info_grid/issues/67) for it.

**Comment by xmonader** [comment]
https://github.com/threefoldtech/info_grid/pull/68 is merged now

**Review by AhmedHanafy725 — APPROVED** [review]

**Pull request merged**
